# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

# Title
name: Agile
subtitle: Principles & Practices.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/agile'

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: index.html
  internal: true

#- text: DOCter Repo
#  url: https://github.com/cfpb/DOCter
#  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: agile
  description: Main repository
  url: https://github.com/18F/agile

# Style Variables
brand_color: "#1188ff"
