# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: pygments

# Title
name: Agile Principles & Practices
subtitle: 

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/agile'

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Principles
  url: principles.html
  internal: true
- text: 1. Define a measurable goal
  url: 1-goal.html
  internal: true
- text: 2. Everyone owns the problem
  url: 2-everyone.html
  internal: true
- text: 3. Small steps with visible impact
  url: 3-steps.html
  internal: true
- text: 4. Validate with your target audience
  url: 4-validate.html
  internal: true
- text: 5. Measure Success
  url: 5-measure.html
  internal: true
- text: 6. Reflect, Adjust, Iterate
  url: 6-iterate.html
  internal: true
- text: Practices
  url: practices.html
  internal: true
#- text: DOCter Repo
#  url: https://github.com/cfpb/DOCter
#  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: agile
  description: Main repository
  url: https://github.com/18F/agile

# Style Variables
brand_color: "#1188ff"
